package oidfconformance_test

// scorecard.go generates `tests/oidf-conformance/SCORECARD.md` as a
// human-readable rollup of the latest harness run. The file is
// committed (not gitignored) so each PR that closes a gap shows up
// in git history as a scorecard diff — "we moved from N/M to N+1/M
// known-gap on the discovery plan" is the right narrative.
//
// Determinism: same harness state + same manifest = byte-identical
// SCORECARD.md. Per-check rows sorted alphabetically by check src.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/panyam/oneauth/tests/oidf-conformance/harness"
)

// scorecardCheck is one row of the per-check status table.
type scorecardCheck struct {
	Src     string
	Status  string // "PASS" | "KNOWN-FAIL" | "KNOWN-WARN" | "REGRESSION" | "RATCHET-UP"
	Issue   int    // gating issue (0 when none — e.g., PASS rows)
	Note    string // one-line summary (trimmed Reason from manifest, or harness msg)
}

// writeScorecard generates SCORECARD.md for the supplied plan. Called
// after the diff completes (regardless of pass/fail) so the scorecard
// reflects the latest observed state. allEntries are the rows to emit
// — derived by the caller from the harness log + manifest.
func writeScorecard(workspaceRoot, plan, testModule string, totals scorecardTotals, rows []scorecardCheck) error {
	sort.Slice(rows, func(i, j int) bool { return rows[i].Src < rows[j].Src })

	var b strings.Builder
	b.WriteString("# OIDF Conformance Scorecard\n\n")
	b.WriteString("Auto-generated by `make testoidf`. Do not edit by hand — rerun the harness instead.\n\n")
	b.WriteString("Source of truth for expected-fails: [`../conformance/known-gaps.yaml`](../conformance/known-gaps.yaml).\n\n")

	b.WriteString("## Plan: `" + plan + "`\n\n")
	b.WriteString("Test module: `" + testModule + "`\n\n")
	b.WriteString("### Summary\n\n")
	b.WriteString("| Metric | Count |\n|---|---|\n")
	b.WriteString(fmt.Sprintf("| Total checks observed | %d |\n", totals.Total))
	b.WriteString(fmt.Sprintf("| Passing | %d |\n", totals.Passes))
	b.WriteString(fmt.Sprintf("| Known gaps (expected-fail in manifest) | %d |\n", totals.KnownGaps))
	b.WriteString(fmt.Sprintf("| Regressions (failed but NOT in manifest) | %d |\n", totals.Regressions))
	b.WriteString(fmt.Sprintf("| Ratchet-up available (in manifest but passed) | %d |\n\n", totals.RatchetUps))

	b.WriteString("### Per-check status\n\n")
	if len(rows) == 0 {
		b.WriteString("(harness emitted no SUCCESS/FAILURE/WARNING entries with a `src` field)\n\n")
	} else {
		b.WriteString("| Check | Status | Gating | Note |\n|---|---|---|---|\n")
		for _, r := range rows {
			issueCell := "—"
			if r.Issue > 0 {
				issueCell = fmt.Sprintf("[#%d](https://github.com/panyam/oneauth/issues/%d)", r.Issue, r.Issue)
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",
				r.Src, r.Status, issueCell, escapeMD(firstLine(r.Note))))
		}
		b.WriteString("\n")
	}

	b.WriteString("### Legend\n\n")
	b.WriteString("- **PASS** — the check ran and passed.\n")
	b.WriteString("- **KNOWN-FAIL / KNOWN-WARN** — the check failed/warned and the manifest documents an expected-fail entry pointing at a gating issue.\n")
	b.WriteString("- **REGRESSION** — the check failed and the manifest has no entry. Build is red.\n")
	b.WriteString("- **RATCHET-UP** — the check passed but the manifest expects failure. Remove the manifest entry. Build is red.\n")

	path := filepath.Join(workspaceRoot, "tests", "oidf-conformance", "SCORECARD.md")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// scorecardTotals is the summary header counts.
type scorecardTotals struct {
	Total       int // distinct check srcs observed
	Passes      int
	KnownGaps   int
	Regressions int
	RatchetUps  int
}

// buildScorecard converts the raw harness log + manifest into the rows
// + totals that writeScorecard consumes. Public so tests can verify
// the row-shape deterministically without driving the live harness.
func buildScorecard(entries []harness.LogEntry, expected map[string]manifestEntry) (scorecardTotals, []scorecardCheck) {
	// Group entries by Src, keeping the worst severity per Src.
	worst := map[string]harness.LogEntry{}
	for _, e := range entries {
		if strings.TrimSpace(e.Src) == "" {
			continue
		}
		if e.Result != harness.ResultSuccess && e.Result != harness.ResultFailure && e.Result != harness.ResultWarning {
			continue
		}
		cur, ok := worst[e.Src]
		if !ok {
			worst[e.Src] = e
			continue
		}
		if severityRank(e.Result) > severityRank(cur.Result) {
			worst[e.Src] = e
		}
	}

	expectedRemaining := map[string]bool{}
	for k := range expected {
		expectedRemaining[k] = true
	}

	var totals scorecardTotals
	var rows []scorecardCheck
	for src, entry := range worst {
		totals.Total++
		switch entry.Result {
		case harness.ResultSuccess:
			row := scorecardCheck{Src: src, Status: "PASS"}
			if _, isExpectedFail := expected[src]; isExpectedFail {
				row.Status = "RATCHET-UP"
				row.Issue = expected[src].Issue
				row.Note = "Now passes; remove manifest entry"
				totals.RatchetUps++
				delete(expectedRemaining, src)
			} else {
				totals.Passes++
			}
			rows = append(rows, row)
		case harness.ResultFailure, harness.ResultWarning:
			row := scorecardCheck{Src: src, Note: entry.Msg}
			if e, ok := expected[src]; ok {
				row.Issue = e.Issue
				if entry.Result == harness.ResultFailure {
					row.Status = "KNOWN-FAIL"
				} else {
					row.Status = "KNOWN-WARN"
				}
				if e.Reason != "" {
					row.Note = e.Reason
				}
				totals.KnownGaps++
				delete(expectedRemaining, src)
			} else {
				row.Status = "REGRESSION"
				totals.Regressions++
			}
			rows = append(rows, row)
		}
	}
	// Manifest-only entries (expected but not observed at all) — emit
	// as RATCHET-UP rows so the scorecard surfaces them.
	for src := range expectedRemaining {
		e := expected[src]
		rows = append(rows, scorecardCheck{
			Src:    src,
			Status: "RATCHET-UP",
			Issue:  e.Issue,
			Note:   "In manifest but not observed; remove entry",
		})
		totals.RatchetUps++
	}
	return totals, rows
}

// severityRank orders results for "worst" comparisons: FAILURE > WARNING
// > SUCCESS. INFO is filtered upstream.
func severityRank(r harness.Result) int {
	switch r {
	case harness.ResultFailure:
		return 3
	case harness.ResultWarning:
		return 2
	case harness.ResultSuccess:
		return 1
	}
	return 0
}

// firstLine returns the first non-empty line of s, with surrounding
// whitespace trimmed. Multi-line manifest `reason:` fields render as
// the first line in the scorecard for compactness.
func firstLine(s string) string {
	for _, line := range strings.Split(s, "\n") {
		if t := strings.TrimSpace(line); t != "" {
			return t
		}
	}
	return ""
}

// escapeMD escapes characters that would break a markdown table cell.
// Conservative: only the pipe (table column delimiter) and backtick
// (code-span boundary inside the backticked check name) need escaping.
func escapeMD(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return s
}

// =============================================================================
// Unit tests — verify buildScorecard's classification + dedup independently of
// the live harness, so future refactors don't drift silently.
// =============================================================================

func TestBuildScorecard_ClassifiesEachCheck(t *testing.T) {
	entries := []harness.LogEntry{
		{Src: "CheckA", Result: harness.ResultSuccess, Msg: "ok"},
		{Src: "CheckB", Result: harness.ResultFailure, Msg: "boom"},
		{Src: "CheckC", Result: harness.ResultWarning, Msg: "soft"},
		{Src: "CheckD", Result: harness.ResultFailure, Msg: "regression"},
		{Src: "CheckE", Result: harness.ResultSuccess, Msg: "ratchet"},
	}
	expected := map[string]manifestEntry{
		"CheckB": {Test: "CheckB", Issue: 116, Reason: "gated on 116"},
		"CheckC": {Test: "CheckC", Issue: 250, Reason: "deployment mode"},
		"CheckE": {Test: "CheckE", Issue: 999, Reason: "stale"},
		"CheckF": {Test: "CheckF", Issue: 777, Reason: "not observed at all"},
	}

	totals, rows := buildScorecard(entries, expected)
	assert.Equal(t, 5, totals.Total, "5 distinct check srcs observed")
	assert.Equal(t, 1, totals.Passes, "only CheckA is an unencumbered pass")
	assert.Equal(t, 2, totals.KnownGaps, "CheckB FAIL + CheckC WARN, both in manifest")
	assert.Equal(t, 1, totals.Regressions, "CheckD fails without manifest entry")
	assert.Equal(t, 2, totals.RatchetUps, "CheckE passes despite manifest entry; CheckF not observed")

	by := map[string]scorecardCheck{}
	for _, r := range rows {
		by[r.Src] = r
	}
	assert.Equal(t, "PASS", by["CheckA"].Status)
	assert.Equal(t, "KNOWN-FAIL", by["CheckB"].Status)
	assert.Equal(t, 116, by["CheckB"].Issue)
	assert.Equal(t, "KNOWN-WARN", by["CheckC"].Status)
	assert.Equal(t, "REGRESSION", by["CheckD"].Status)
	assert.Equal(t, "RATCHET-UP", by["CheckE"].Status, "passes despite manifest entry")
	assert.Equal(t, "RATCHET-UP", by["CheckF"].Status, "manifest entry with no observation")
}

func TestBuildScorecard_PromotesToWorstSeverity(t *testing.T) {
	entries := []harness.LogEntry{
		{Src: "MultiCheck", Result: harness.ResultWarning, Msg: "first warning"},
		{Src: "MultiCheck", Result: harness.ResultFailure, Msg: "later failure"},
		{Src: "MultiCheck", Result: harness.ResultSuccess, Msg: "earlier success"},
	}
	totals, rows := buildScorecard(entries, map[string]manifestEntry{})
	require.Len(t, rows, 1, "single distinct Src")
	assert.Equal(t, "REGRESSION", rows[0].Status,
		"failure should outrank success and warning")
	assert.Equal(t, 1, totals.Regressions)
}

func TestFirstLine_PrefersFirstNonEmpty(t *testing.T) {
	assert.Equal(t, "first content", firstLine("\n\n   first content\nsecond\n"))
	assert.Equal(t, "", firstLine(""))
	assert.Equal(t, "", firstLine("\n  \n\t\n"))
}

func TestEscapeMD_EscapesPipeOnly(t *testing.T) {
	assert.Equal(t, `safe text`, escapeMD("safe text"))
	assert.Equal(t, `a \| b \| c`, escapeMD("a | b | c"))
}
