package utils

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"

	"github.com/golang-jwt/jwt/v5"
)

// GenerateRSAKeyPair generates an RSA key pair and returns PEM-encoded private and public keys.
func GenerateRSAKeyPair(bits int) (privPEM, pubPEM []byte, err error) {
	priv, err := rsa.GenerateKey(rand.Reader, bits)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate RSA key: %w", err)
	}
	privPEM = EncodePrivateKeyPEM(priv)
	pubPEM, err = EncodePublicKeyPEM(&priv.PublicKey)
	if err != nil {
		return nil, nil, err
	}
	return privPEM, pubPEM, nil
}

// GenerateECDSAKeyPair generates an ECDSA P-256 key pair and returns PEM-encoded private and public keys.
func GenerateECDSAKeyPair() (privPEM, pubPEM []byte, err error) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate ECDSA key: %w", err)
	}
	privPEM = EncodePrivateKeyPEM(priv)
	pubPEM, err = EncodePublicKeyPEM(&priv.PublicKey)
	if err != nil {
		return nil, nil, err
	}
	return privPEM, pubPEM, nil
}

// ParsePublicKeyPEM parses a PEM-encoded public key (RSA or ECDSA).
func ParsePublicKeyPEM(pemBytes []byte) (crypto.PublicKey, error) {
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return nil, fmt.Errorf("failed to decode PEM block")
	}
	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse public key: %w", err)
	}
	return pub, nil
}

// ParsePrivateKeyPEM parses a PEM-encoded private key (RSA or ECDSA, PKCS8 format).
func ParsePrivateKeyPEM(pemBytes []byte) (crypto.PrivateKey, error) {
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return nil, fmt.Errorf("failed to decode PEM block")
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse private key: %w", err)
	}
	return key, nil
}

// EncodePublicKeyPEM encodes a crypto.PublicKey to PEM format.
func EncodePublicKeyPEM(pub crypto.PublicKey) ([]byte, error) {
	der, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal public key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{
		Type:  "PUBLIC KEY",
		Bytes: der,
	}), nil
}

// EncodePrivateKeyPEM encodes a crypto.PrivateKey to PKCS8 PEM format.
func EncodePrivateKeyPEM(priv crypto.PrivateKey) []byte {
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		// Should not happen for RSA/ECDSA keys generated by this package
		panic(fmt.Sprintf("failed to marshal private key: %v", err))
	}
	return pem.EncodeToMemory(&pem.Block{
		Type:  "PRIVATE KEY",
		Bytes: der,
	})
}

// DecodeVerifyKey converts raw key material from a KeyStore into the appropriate
// type for JWT verification based on the algorithm.
//   - For HMAC algorithms (HS256/HS384/HS512): returns the key as-is (expected to be []byte)
//   - For RS256: if key is []byte, parses as PEM to *rsa.PublicKey; if already *rsa.PublicKey, returns as-is
//   - For ES256: if key is []byte, parses as PEM to *ecdsa.PublicKey; if already *ecdsa.PublicKey, returns as-is
func DecodeVerifyKey(rawKey any, alg string) (any, error) {
	if !IsAsymmetricAlg(alg) {
		return rawKey, nil
	}

	switch alg {
	case "RS256":
		switch k := rawKey.(type) {
		case *rsa.PublicKey:
			return k, nil
		case []byte:
			pub, err := ParsePublicKeyPEM(k)
			if err != nil {
				return nil, fmt.Errorf("RS256: %w", err)
			}
			rsaPub, ok := pub.(*rsa.PublicKey)
			if !ok {
				return nil, fmt.Errorf("RS256: expected RSA public key, got %T", pub)
			}
			return rsaPub, nil
		default:
			return nil, fmt.Errorf("RS256: unsupported key type %T", rawKey)
		}
	case "ES256":
		switch k := rawKey.(type) {
		case *ecdsa.PublicKey:
			return k, nil
		case []byte:
			pub, err := ParsePublicKeyPEM(k)
			if err != nil {
				return nil, fmt.Errorf("ES256: %w", err)
			}
			ecPub, ok := pub.(*ecdsa.PublicKey)
			if !ok {
				return nil, fmt.Errorf("ES256: expected ECDSA public key, got %T", pub)
			}
			return ecPub, nil
		default:
			return nil, fmt.Errorf("ES256: unsupported key type %T", rawKey)
		}
	default:
		return nil, fmt.Errorf("unsupported algorithm: %s", alg)
	}
}

// IsAsymmetricAlg returns true if the algorithm uses asymmetric keys (RS256, ES256).
func IsAsymmetricAlg(alg string) bool {
	return alg == "RS256" || alg == "ES256"
}

// SigningMethodForAlg returns the jwt.SigningMethod for the given algorithm string.
func SigningMethodForAlg(alg string) jwt.SigningMethod {
	switch alg {
	case "RS256":
		return jwt.SigningMethodRS256
	case "ES256":
		return jwt.SigningMethodES256
	case "HS384":
		return jwt.SigningMethodHS384
	case "HS512":
		return jwt.SigningMethodHS512
	default:
		return jwt.SigningMethodHS256
	}
}
